### ISSUE TITLE
Add better caching for directory sources

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#102]
Currently, directory sources can't properly be cached due to build-affecting changes outside the needs configuration.

**Comment by ccbrown** [comment]
I've been considering making directory sources do a copy instead of making a symlink. That fixes this and a few other things. It'll make builds a little slower and take more disk space, but I think it's the right thing to do.

**Comment by vmrob** [comment]
It would be pretty trivial to maintain a copy using rsync. The only real problem is determining a portable way to determine how to make those contents cacheable. I might suggest something like storing a manifest of individual file hashes. By using the `--itemize-changes` flag for rsync, it appears it would be pretty easy to rehash updated files.

Essentially, the configuration hash for a directory source would be a hash of the configuration + a hash of all of the file contents in the directory.

**Comment by ccbrown** [comment]
Merged into #108
