### ISSUE TITLE
Add caching of sources

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#103]
For downloads, caching should be trivial. For directory sources, see #102. For git sources, externalizing the git directory and storing that might be the easiest thing to do.

**Comment by ccbrown** [comment]
Can you elaborate a bit on this?

Downloads are already cached. And Git repos persist as well. What exactly is the suggestion?

**Comment by vmrob** [comment]
I'm specifically referring to making them available via the cache that needy provides so that the same download found in multiple needs configurations can be reused instead of downloaded multiple times. For larger libraries used in multiple places, this could result in several hundred megabytes of space saved (ie. boost) and when remote caching is implemented, it will act as a built in re-uploading mechanism in case a specific source becomes unavailable for some period of time.

**Comment by ccbrown** [comment]
Merged into #108
