### ISSUE TITLE
Add needy clean

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#109]
There are cases where it would be desirable to download sources and perform the initial clean steps for one or more libraries. As an example, dev-mode requires the source to be in this state.

```
needy clean
needy clean libfmt
needy clean libfmt -t android
```

**Comment by ccbrown** [comment]
Added in 9e32a44a0fbf647e4a055dcae62508598774f48b, name second-guessed in 00fc4346fafde77e01dd73152346b9a464dc6b79.

Avoiding "clean" because it has a pretty distinct meaning in the context of builds. Going with "init". The fetch + clean + post-clean operations will make up this initialization.
