### ISSUE TITLE
Source linking doesn't work on Mac

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#121]
>['ar', '-rv', '-o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/lib/liblua.a', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lapi.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lauxlib.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lbaselib.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lbitlib.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lcode.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lcorolib.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lctype.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/ldblib.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/ldebug.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/ldo.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/ldump.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lfunc.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lgc.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/linit.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/liolib.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/llex.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lmathlib.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lmem.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/loadlib.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lobject.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lopcodes.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/loslib.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lparser.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lstate.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lstring.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lstrlib.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/ltable.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/ltablib.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/ltm.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lundump.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lvm.o', u'/var/folders/3t/080l6nyn4cncynjmgk3g_jp00000gn/T/tmpv2AEJn/needs/lua/build/osx/x86_64/obj/lzio.o']

```
ar: illegal option combination for -r
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
```

**Comment by ccbrown** [comment]
Fixed by 5fdec402cbbc39dba646f4c42ba5689207fcb77b.
