### ISSUE TITLE
Race condition in pkgconfig.jam

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#126]
When packages refer to the same build directory, a race condition exists when a threaded b2 invocation attempts to copy files at the same time. Example:

install targets in pkgconfig.jam
```
actions install-libavformat-package-action { mkdir -p $(INSTALL_PREFIX) && cp -pR /app/needs/ffmpeg/build/osx/x86_64/* $(INSTALL_PREFIX)/ }
actions install-libavcodec-package-action { mkdir -p $(INSTALL_PREFIX) && cp -pR /app/needs/ffmpeg/build/osx/x86_64/* $(INSTALL_PREFIX)/ }
```

Jamroot
```
pkgconfig.dependency ffmpeg : libavcodec libavutil libavformat libswresample libswscale ;
```

When the copy step occurs, these targets are obviously identical, but two separate actions are performed. The second, if it occurs at roughly the same time as the first, will fail:

```
01:29:23.308 pkgconfig.install-libavcodec-package-action <l./clang-linux-needy/release/address-model-64/architecture-x86>install-libavcodec-package
01:29:23.308 cp: cannot create regular file ‘/foo/needs/app/build/generic/x86_64/release/lib/pkgconfig/libavutil.pc’: File exists
01:29:23.308  mkdir -p /foo/needs/app/build/generic/x86_64/release && cp -pR /foo/needs/avpipeline/needs/ffmpeg/build/generic/x86_64/* /foo/needs/app/build/generic/x86_64/release/ 
01:29:23.308 ...failed pkgconfig.install-libavcodec-package-action <l./clang-linux-needy/release/address-model-64/architecture-x86>install-libavcodec-package...
01:29:23.308 pkgconfig.install-libavutil-package-action <l./clang-linux-needy/release/address-model-64/architecture-x86>install-libavutil-package
01:29:23.308 cp: cannot create regular file ‘/foo/needs/app/build/generic/x86_64/release/lib/libswresample.a’: File exists
01:29:23.309 cp: cannot create regular file ‘/foo/needs/app/build/generic/x86_64/release/needy.status’: File exists
01:29:25.275  mkdir -p /foo/needs/app/build/generic/x86_64/release && cp -pR /foo/needs/avpipeline/needs/ffmpeg/build/generic/x86_64/* /foo/needs/app/build/generic/x86_64/release/ 
01:29:25.275 ...failed pkgconfig.install-libavutil-package-action <l./clang-linux-needy/release/address-model-64/architecture-x86>install-libavutil-package...
```

This can lead to sporadic build failures reported by b2.

**Comment by ccbrown** [comment]
Yeah... I've seen this. The real race condition is actually in `cp`. It's supposed to ignore files that already exist. But if the file gets placed there between cp checking for its existence and trying to write it, cp errors out.

I think the easy thing to do here is to actually just ignore the error. One of the cp commands will succeed, and the other is redundant anyways.

**Comment by vmrob** [comment]
For platforms that have symlinks, an atomic swap is definitely possible, but I don't think that's necessary. For a needy solution, I think a modification to the generator to have multiple targets use a single base rule for the copy would be both faster and more robust. No comment on implementation difficulty though--I haven't looked at the pkgconfig generation code.

**Comment by ccbrown** [comment]
Not using symlinks. Avoiding redundant copies would, of course, be preferable and was something I wanted to do when I wrote the generator. But implementation difficulty is, unfortunately, a real factor when it comes to anything Boost.Build related. ;_;

**Comment by vmrob** [comment]
I'm going to try my luck at adding a second set of rules to the pkgconfig generator. The idea will basically look something like this:

```
for path in unique_source_paths:
    hash_of_path = sha256(path)
    contents += 'actions copy-path-{hash_of_path} { mkdir -p $(INSTALL_PREFIX) && cp -pR {path}/* $(INSTALL_PREFIX)/ }'.format(hash_of_path=hash_of_path, path=path)
```

Farther down...

```
hash_of_path = sha256(path)
contents += 'alias install-{package}-package-if-owned : copy-path-{hash_of_path};\n'.format(package=package, hash_of_path=hash_of_path)
```

Something like that. I'm thinking it will at least prevent obvious collisions.

**Comment by vmrob** [comment]
I think #128 will resolve this issue for common use cases. I would expect that there are still weird edge cases to consider.
