### ISSUE TITLE
When a lib has a Needy dependency, building the lib via b2 doesn't build the dependency

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#37]
As stated in the title, when a lib has a Needy dependency, building the lib via b2 doesn't appear to build the dependency. The workaround is to invoke b2 multiple times.

**Comment by vmrob** [comment]
I'll come up with a minimal test case later if it's necessary.

**Comment by ccbrown** [comment]
Problem boils down to this: When specifying a specific library or filter, dependencies are not implicitly included in the build. They should be.

**Comment by ccbrown** [comment]
Turns out this was a user error: putting the "dependencies" key in the wrong location. I've committed a test to verify that this works: 179dadef3df71165fb2d7247606dfae3ff2f261b

And I'm creating another task to give the user some feedback for unused configuration parameters: #38
