### ISSUE TITLE
Provide feedback for unused / misplaced configuration parameters

### ISSUE THREAD

**Issue by ccbrown** [ccbrown/needy#38]
To be a little more helpful for typos or hierarchy mistakes.

**Comment by ccbrown** [comment]
bb8d50b8be3f66925d61683a60e2bed166ab2743 now errors out for unrecognized project configuration keys

**Comment by vmrob** [comment]
Should this be closed?

**Comment by ccbrown** [comment]
There are a few things that aren't yet covered by this.

**Comment by ccbrown** [comment]
Consolidating into #106
