### ISSUE TITLE
Add a Needy distribution egg/zip

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#55]
Instead of a submodule, a single file should be committed to repositories that depend on Needy. A python egg or zip (I've read that a zip with a `__main__.py` works as expected) would be ideal.

**Comment by ccbrown** [comment]
This already works:

`./setup.py bdist_egg`
`PYTHONPATH=dist/needy-0.0-py2.7.egg python -m needy`

So I guess you're just suggesting adding a \__main\__.py to the root of the egg with `import needy.__main__` for a simpler invocation. Right?

If so, that's pretty trivial. I'd probably knock that out pretty soon.

**Comment by vmrob** [comment]
Yes. Basically just adding the __main__.py for simpler invocation. I think adding a means to generate that file via needy (as opposed to an arcane python command) would be greatly appreciated by people used to working with gradle projects.

**Comment by ccbrown** [comment]
I'll add the \__main\__ and document the egg generation for now. I'm hesitant to start adding convenience wrappers for Python commands like that.

**Comment by vmrob** [comment]
Yup. As long as they're documented in an easy-to-access place, I don't think there's a problem.

**Comment by ccbrown** [comment]
Resolved via d5aa88596a67b45a0c0b9756b89e29bdbfe8197b:

`./setup.py bdist_egg`
`chmod +x ./dist/needy-0.0-py2.7.egg`
`./dist/needy-0.0-py2.7.egg help`

**Comment by ccbrown** [comment]
And made a bit better with 883e407f64aecd73344177a095b0fe683f2d2842.

**Comment by vmrob** [comment]
Very cool. This will greatly simplify our Needy distributions.
