### ISSUE TITLE
Scan all files only when library is in dev mode

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#60]
`local files = [ SPLIT_BY_CHARACTERS [ SHELL "find $(sourcedir) -type f -not -path '*/\.*' 2> /dev/null" ] : "\n" ] ;`

This drastically increases the runtime of b2 operations and seems to only be necessary for dev-mode libraries. b2 should query Needy for a library's dev-mode status before scanning all of the files.

**Comment by ccbrown** [comment]
Fixed by 9e16022ecb7718cb3396247172b9787404fa23f4.
