### ISSUE TITLE
Faster git sources

### ISSUE THREAD

**Issue by ccbrown** [ccbrown/needy#63]
The most common case for git source is just fetching a single commit. For these cases, we can do better than a full clone.

**Comment by vmrob** [comment]
This may not be possible for specific commits, but it's definitely possible for branch heads.

http://stackoverflow.com/questions/26135216/why-isnt-there-a-git-clone-specific-commit-option

**Comment by vmrob** [comment]
Should Needy support branch heads? I don't like it.

**Comment by ccbrown** [comment]
This may go on the roadmap if there's greater motivation, but for now, I have no plans for this.
