### ISSUE TITLE
Better handling of artifacts with incorrect checksums

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#72]
When Needy finds that an artifact has an incorrect checksum but hasn't downloaded it, it should attempt to re-download it after determining the checksum is incorrect.

A related issue is that needy doesn't appear to try to re-download artifacts if the checksum is declared the same between changes in build configuration. Specifically, if the download URL changes, Needy should probably re-download the artifact.

**Comment by ccbrown** [comment]
I think the bug here is that the local file is index by the expected checksum rather than the actual checksum. Will fix soon.

**Comment by ccbrown** [comment]
Resolved via c0790c9ac3beb9027bd1155afc7db35d3eb4a909.

Not even gonna keep downloads with incorrect checksums. And with that fixed, I'm pretty sure there's no valid case for re-downloading if the URL changes, but the checksum doesn't.
