### ISSUE TITLE
Add remote cache implementation

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#80]
Needy should be able to publish built artifacts to s3 and should probably use a redis server to implement the required file locking. Additionally, needy should support lock-free read-only of the same s3 cache.

The use case here is that if a development team has a ci server they wouldn't mind receiving pre-built artifacts from, they could have read-only access to the s3 cache for published artifacts while the ci server provides those artifacts to s3.

**Comment by ccbrown** [comment]
I'm going to rename this from "Add s3 cache support" to "Add remote cache implementation". I want the functionality, but I want to evaluate whether s3+locking server is the best solution.

**Comment by ccbrown** [comment]
Merged into #108
